version: "3.7"

networks:
  default:
    driver: bridge

services:
  locator:
    image: apachegeode/geode
    hostname: locator
    container_name: geode_locator
    expose:
      - "10334"
      - "1099"
      - "7575"
    #  - "1024"
    ports:
      - "1099:1099"
      - "10334:10334"
      - "7575:7575"
      - "7070:7070"
    volumes:
      - ./scripts:/scripts/
    command: /scripts/gfshWrapper.sh gfsh start locator --hostname-for-clients=localhost --jmx-manager-hostname-for-clients=localhost --J=-Djava.rmi.server.hostname=localhost

  server:
    image: apachegeode/geode
    hostname: server
    container_name: geode_server
    depends_on:
      - locator
    links:
      - locator:locator
    expose:
      - "8080"
      - "40404"
      - "1099"
    ports:
      - "40404:40404"
    volumes:
      - ./scripts:/scripts/
    command: /scripts/startServer.sh --server-port=40404 --max-heap=1G
